### ISSUE TITLE
Add GDS support to Htsget Stack

### ISSUE THREAD

**Issue by victorskl** [umccr/infrastructure#196]
**Context:**

- Like S3; add support **private files** serving from GDS for [htsget CDK stack](https://github.com/umccr/infrastructure/tree/master/cdk/apps/htsget)

**Actions:**

- Explore, propose and apply the solution

**Comment by victorskl** [comment]
Put this on hold for 2 reasons:

- GDS will be gone away with ICA v2
- Instead of keep brushing up htsget RI instances, we shall redirect all our effects into #214

/cc @ohofmann @brainstorm @andrewpatto

**Comment by brainstorm** [comment]
Related: https://github.com/umccr/htsget-rs/issues/71, @mmalenic is working on the S3 storage layer right now.

**Comment by brainstorm** [comment]
If GDS is gone with ICA v2, what's a substitute storage abstraction that we could wrap use for htsget?

**Comment by victorskl** [comment]
> If GDS is gone with ICA v2, what's a substitute storage abstraction that we could wrap use for htsget?

AFAIK, there is no substitute storage abstraction in v2. 

The closest we can reckon seemingly [ProjctData](https://ica.illumina.com/ica/api/swagger/index.html#/Project%20Data) endpoint. Meanwhile, @alexiswl propose URI scheme https://github.com/umccr-illumina/ica_v2/issues/96 due to this  reason.

In `libica`, I came up with [App package](https://github.com/umccr-illumina/libica/blob/2.0.0/libica/app/__init__.py) idea (i.e. custom implementations on top of autogen API/SDK) and, there is [dataops](https://github.com/umccr-illumina/libica/blob/2.0.0/libica/app/dataops.py) module and, [ProjectDataOps](https://github.com/umccr-illumina/libica/blob/2.0.0/libica/app/dataops.py#L18) implementation for [backward GDS compatibility](https://github.com/umccr-illumina/libica/blob/2.0.0/libica/app/gds.py).  

And, usage of this `ProjectDataOps` implementation is demostrated in [pilotapp module](https://github.com/umccr-illumina/libica/blob/2.0.0/pilotapp.py).

**Comment by victorskl** [comment]
Updates:

- As discussed with Roman; for now for htsget-rs, we will go ahead with v1 GDS implementation -- which is [WIP here](https://github.com/umccr/htsget-rs/pull/88).
- Mainly based on pragmatic reason such that our data will be sit in GDS for awhile...
- Roman also created [Rust SDK for ICA v1](https://github.com/umccr-illumina/ica-rs).

**Comment by victorskl** [comment]
Update:

- As deprecating htsget-go RI instance in favour of htsget-rs, we are in the progress of winding down [htsget-go RI CDK deployment ECS stack](https://github.com/umccr/infrastructure/tree/master/cdk/apps/htsget)
- Hence, won't fix/work on original task of this issue i.e. not needing to update htsget cdk app in this infra repo
- I will close this issue with deprecation PR note in tick, next
