### ISSUE TITLE
Setup Cognito AAI - To refactor out from Portal Stack

### ISSUE THREAD

**Issue by victorskl** [umccr/infrastructure#217]
**Context:**

- Likewise to centralise [Networking stack](https://github.com/umccr/infrastructure/tree/master/terraform/stacks/networking) for housing Application networking need, refactor out Cognito resources from Portal stack to cater for more centralise UMCCR-wide Cognito AAI setup
- So that various dispersed UMCCR-wide App can re-use Cognito AAI setup; will have Standard SOP for AuthN/Z

**Current Userland:**

- Portal
- Htsget
- Status
- SampleSheet Checker
- Illumination

**Actions:**

- Refactor out Terraform code related to Cognito resources from [Portal stack](https://github.com/umccr/infrastructure/tree/master/terraform/stacks/umccr_data_portal)
- TF import existing states DEV/PROD
- Like Networking, this can still be terraformed!

**Comment by williamputraintan** [comment]
So from the `data-portal` Cognito, I think we could remove the Cognito Identity Pool resource and use Cognito User Pool itself is enough for authenticating. The Identity Pool is used to add more policy to the authenticated user (something like invoking lambda, accessing s3, etc.), but in our case we only use Cognito for authentication for UMCCR accounts.

The data-portal did have [identity-pool](https://github.com/umccr/infrastructure/blob/91453a1eb4bfa5a5e13665c005a0d2f159a74f0e/terraform/stacks/umccr_data_portal/main.tf#L376-L430) defined, which is used at the [portal client](https://github.com/umccr/data-portal-client/blob/89881242362822e3a3c9b56ab0c0969da432494c/src/index.js#L20). But from other stacks (such as[ status-page](https://github.com/umccr/data-portal-status-page/blob/dfc57b3929a8dd16647038d3e9eacccea009e494/src/index.js#L13-L17) or [sscheck](https://github.com/umccr/samplesheet-check-frontend/blob/994a1c97b8007294f1271ed9329cb6f6148ce20e/src/index.js#L11-L15)), it is actually not a compulsory [field](https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) if do not want to use identit-pool.

By this we could have CognitoUserPool stack defined here, and any configuration needed to the app could be defined at the application stack (by using the CognitoUserrPool LookUp functions). This would allow this stack not being re-deploy/modify here, instead they would just add from their own stack. At time being, Cognito Identity pool have no easy way on adding client app at a different stack (Might need re-deploy for a change in Cognito Identity Pool). 

I might be wrong, but happy for any comments.

**Comment by victorskl** [comment]
Yep; you understood correct and point noted, Will.  

We shall revisit in future the need of central identity pool, or otherwise. 

For now, we shall focus on refactor & migrate TF state as-is to separate stack.

As discussed; let me take it from there. It will get a bit touchy with state import. 

Thanks for the try!
