### ISSUE TITLE
Update WTS multiQC config value

### ISSUE THREAD

**Issue by skanwal** [umccr/infrastructure#277]
```
 I've just noticed that the order and naming of samples on the RNA multiQC report for SBJ02999 are different from the last case I looked at. Do you know why this is? It's no issue as I can still see which was the 'bad' reference sample and just need to check the metrics for my sample. 
 ```

We had updated the reference samples for WTS-QC pipeline to resolve https://github.com/umccr/cwl-ica/issues/120.
As a result of this update, I had updated output file names for WTS QC reference samples. We need to reflect this change in `cl_config` option for multiQC step. That is update:

```
"cl_config": "{\"sample_names_replace\":{\"L2200121\":\"Ref_1_Good\",\"L2101521\":\"Ref_2_Good\",\"L2200188\":\"Ref_3_Good\",\"L2101763\":\"Ref_4_Bad\",\"L2200311\":\"Ref_5_Bad\"}}"
```

to 

```
"cl_config": "{\"sample_names_replace\":{\"PRJ220412\":\"Ref_1_Good\",\"MDX210318\":\"Ref_2_Good\",\"PRJ220466\":\"Ref_3_Good\",\"PRJ211234\":\"Ref_4_Bad\",\"PRJ220790\":\"Ref_5_Bad\"}}"
```

in [wts_tumor_only_dev.json](https://github.com/umccr/infrastructure/blob/master/terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_dev.json), [wts_tumor_only_prod.json](https://github.com/umccr/infrastructure/blob/master/terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_prod.json) and [wts_tumor_only_stg.json](https://github.com/umccr/infrastructure/blob/master/terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_stg.json).

**Comment by alexiswl** [comment]
Just having a look through the report now - 

Looks like the qualimap doesn't refer to the new reference names though - 

![image](https://user-images.githubusercontent.com/8197659/218631626-0e38e02e-ef3b-4e19-bc8a-8f0d659fe8ed.png)

From the workflow inputs

```bash
ica workflows runs get \
   --output-format json \
  wfr.6cc0fc8a02c14310824a7c4500dfa768 | \
jq --raw-output \
  '
    .input | 
    fromjson | 
    .qc_reference_samples | 
    map(.location)
  '
```

Yields

```
[
  "gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01563",
  "gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01147",
  "gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01620",
  "gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01286",
  "gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01673"
]
```

If we have a look at one of the qualimap samples in here:

```
$ gds-ls gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01286/
```

Yields

```
gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01286/L2101763_dragen/
gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01286/L2101763_dragen_qualimap/
gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01286/_manifest.json
gds://development/reference-data/dragen_wts/multiqc/2022-09-14--3.9.3/SBJ01286/_tags.json
```

But for the regular workflow, the output directory for the qualimap sample is:
```
ica workflows runs get \
  --output-format json \
  wfr.6cc0fc8a02c14310824a7c4500dfa768 | \
jq --raw-output \
  '
    .output | fromjson | 
    .qualimap_output_directory.location
  '
```

Yields

```
gds://development/temp/sehrish/dragne_wts_debug_qc/MDX210377/MDX210377_qualimap
```

Not
```
gds://development/temp/sehrish/dragne_wts_debug_qc/MDX210377/MDX210377_dragen_qualimap
```

Might need to re-run the workflows for the qc-reference-samples to ensure that the output directory doesn't have the __dragen_ midfix.

**Comment by skanwal** [comment]
One thing sorted and another one broke 😖.  I'll update results for reference data as well.

**Comment by skanwal** [comment]
@alexiswl - also wondering if I should generate results for reference data using Dragenv4? Do we plan to upgrade Dragen workflows for this upcoming portal release?

**Comment by alexiswl** [comment]
One for the group meeting I think
