### ISSUE TITLE
Extend map_fastq.py script for Dragen-wts workflow

### ISSUE THREAD

**Issue by skanwal** [umccr/infrastructure#28]
The plan is to extend https://github.com/umccr/infrastructure/blob/master/scripts/showcase/map_fastqs.py script to include an option for WTS fastq mapping that can prepare the arguments for Dragen WTS data analysis step, specifically input for `--fastq-list` parameter. Details  [here](https://github.com/umccr-illumina/stratus/blob/master/showcase/wts/wfv.json#L210) 

ping - @alexiswl

**Comment by alexiswl** [comment]
Thanks Sehrish, can I confirm it has the same columns as the WGS files?
```
RGID, RGSM, RGLB, Lane, Read1File, Read2File
```

**Comment by skanwal** [comment]
Yes, it has the same column headers for WTS.

**Comment by alexiswl** [comment]
Cool, done with #31 

I've done two tasks that successfully complete both options using different `workflow-type` parameters,

```
trn.d38c52049f1049a6a8b2145f871aab7c
trn.57bf4d80d70f4ff5b3563e0cb5035eed
```
