### ISSUE TITLE
Bootstrap CDK in accounts without using the CLI tool

### ISSUE THREAD

**Issue by andrewpatto** [umccr/infrastructure#350]
The CDK cli can bootstrap an account but is prone to configuration drift when (future) devs
try to upgrade it. Better to tell everyone never to use the CLI for bootstrapping and
have it done via terraform

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UoM AWS Migration: Bootstrap CDK in new UoM AWS accounts](https://trello.com/c/jn56wL6f/1439-uom-aws-migration-bootstrap-cdk-in-new-uom-aws-accounts)
