### ISSUE TITLE
Install an IAM user into UoM accounts so that Elsa Data can use for signing

### ISSUE THREAD

**Issue by andrewpatto** [umccr/infrastructure#361]
Elsa Data needs an escape hatch from the normal short lived credentials in order to sign (longer) lived URLs for objects.

To do this is has a CDK stack that creates a suitable IAM user - but this is not allowed for deployment to UoM.

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UoM AWS Migration: Create new AWS account for dedicated Demo stack](https://trello.com/c/2peVjtHU/1537-uom-aws-migration-create-new-aws-account-for-dedicated-demo-stack)
