### ISSUE TITLE
TF data archive: bucket policies with invalid principals

### ISSUE THREAD

**Issue by reisingerf** [umccr/infrastructure#441]
The bucket policies for the [staging](https://github.com/umccr/infrastructure/blob/032d74687162548ceb8900f11d5f775b539a1fcd/terraform/stacks/data_archive/byob_ica_v2.tf#L404-L419) and [production](https://github.com/umccr/infrastructure/blob/032d74687162548ceb8900f11d5f775b539a1fcd/terraform/stacks/data_archive/byob_ica_v2.tf#L268-L283) ICAv2 cache buckets refer to roles that have not yet been created and are therefore invalid in the resource policy.

**Comment by victorskl** [comment]
Related #440
