### ISSUE TITLE
Add s3 bucket read permission for role authenticated policy

### ISSUE THREAD

**Issue by raylrui** [umccr/infrastructure#449]
### Context:
For [static report issue](https://github.com/umccr/data-portal-status-page/issues/108), we need have bucket "read permission" (List and get objects) for role authenticated policy of our identity pool.

### Action:
Add ["s3:ListBucket","s3:GetObject"], for our user pool policy.

**Comment by victorskl** [comment]
This issue too @raylrui ?

**Comment by raylrui** [comment]
yes, will close as well, thanks
