### ISSUE TITLE
Add VPCs etc for enclave and data-control

### ISSUE THREAD

**Issue by andrewpatto** [umccr/infrastructure#515]
We will be running _some_ compute in enclave and data-control - so we need to spin up terraform vpcs etc (main-vpc).

Basically whatever the standard is.

Also, can't remember whether terraform also triggers the CDK bootstrap

**Comment by victorskl** [comment]
All done and bootstrap.

**Comment by andrewpatto** [comment]
Thanks - have deployed to data-control and all is working. Closing
