### ISSUE TITLE
Error with the overridecycles settings for split sheets 

### ISSUE THREAD

**Issue by skanwal** [umccr/infrastructure#77]
@alexiswl  - I have re-run conversion for run141 on IAP to reproduce and debug the error we have recently encountered as part of **Portal Workflow Automaton**. 

Seems when writing `SampleSheet_WTS.*.*.csv`, the [script](https://github.com/umccr/infrastructure/blob/master/scripts/showcase/samplesheet-prep-test.py) doesn’t add N  to overridecycles settings. 

Example:

The script is adding  `OverrideCycles,Y151;I8;I8;Y151`  instead of `OverrideCycles,Y151;I8N2;I8N2;Y151` to split sheet with WTS samples, resulting in the following error:

```
Sample sheet being processed by common lib? No\nERROR: in OverrideCycles: Read # 2 specified does not add up to the 10 bases expected from RunInfo.xml
```

The splitsheet with WGS samples is created with correct OverrideCycles.

Reference for workflow run:

- `wfr.52b2a210c5fe46ee98397c93f77931e0`
-  failed task run with WTS sheet `trn.105b0bae56ed427b9313f6e76d71d172`
- in-progress run with WGS sheet `trn.105b0bae56ed427b9313f6e76d71d172`

**Comment by alexiswl** [comment]
Looking at the original samplesheet - from `gds://bssh.acddbfda498038ed99fa94fe79523959/Runs/200911_A00130_0141_AH5LYMDSXY_r.v0_3LvA8E0y9SvJxZLBeFA/SampleSheet.csv`

Shown below are the erroring samples
```
4,MDX200151_L2000757,L2000757,,,D02,UDI0012,CTCTCGTC,UDI0012,TATAACCT,VCCC,PO
4,MDX200154_L2000758,L2000758,,,E02,UDI0013,CCAAGTCT,UDI0013,AAGGATGA,VCCC,PO
4,PRJ200408_L2000759,L2000759,,,F02,UDI0014,TTGGACTC,UDI0014,GGAAGCAG,Tothill,NET
4,PRJ200419_L2000760,L2000760,,,G02,UDI0015,GGCTTAAG,UDI0015,TCGTGACC,Tothill,CUP
4,PTC_TsqSTR200908VD_L2000761,L2000761,,,H02,UDI0016,AATCCGGA,UDI0016,CTACAGTT,UMCCR,Control
4,NTC_TsqSTR200908VD_L2000762,L2000762,,,A03,UDI0017,TAATACAG,UDI0017,ATATTCAC,UMCCR,Control
```

These should be instead:
```
4,MDX200151_L2000757,L2000757,,,D02,UDI0012,CTCTCGTC,UDI0012,TATAACCTNN,VCCC,PO
4,MDX200154_L2000758,L2000758,,,E02,UDI0013,CCAAGTCT,UDI0013,AAGGATGANN,VCCC,PO
4,PRJ200408_L2000759,L2000759,,,F02,UDI0014,TTGGACTC,UDI0014,GGAAGCAGNN,Tothill,NET
4,PRJ200419_L2000760,L2000760,,,G02,UDI0015,GGCTTAAG,UDI0015,TCGTGACCNN,Tothill,CUP
4,PTC_TsqSTR200908VD_L2000761,L2000761,,,H02,UDI0016,AATCCGGA,UDI0016,CTACAGTTNN,UMCCR,Control
4,NTC_TsqSTR200908VD_L2000762,L2000762,,,A03,UDI0017,TAATACAG,UDI0017,ATATTCACNN,UMCCR,Control
```

The samplesheet-split script for the 1.0.4 version needs the Ns to know how many cycles are in the original index for each sample. This should probably be done as a check at the start and thus fail if all of the index cycles don't add up to the same number. Would you mind retrying with these amendments to the samplesheet and I'll look at putting in a check for that.

**Comment by skanwal** [comment]
Thanks for looking @alexiswl .

Looking through the WGS samples in the original samplesheet, the indexes seem to correctly have `N's`  in both I5 and I7 index columns.

I can try manually editing the copy of original samplesheet but this is something we should probably report back to Kym and team.

cc - @reisingerf & @ohofmann

**Comment by reisingerf** [comment]
I checked with the lab, that was a mistake on their side and should not have happened.
The SampleSheet was not the final version....

**Comment by skanwal** [comment]
Thanks, Florian for confirming with the lab.

At-least, the exercise helped us find another check that we should probably add in the samplesheet check stage in the current workflow iteration.

 I'll close this issue for now.
